location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: nodelet
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: 86cb0e30f451b00efc6a69259cfa767848122e10
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: f99cb0e709fa7565ceb46f29fd4d1ddcfd3d5d73
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: 2aad4784637300c47de4648467730276024f406e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: 6c27d9e55d50462e7cdade337b3e2225435ecfbb
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: dd6e9545257512a260f2aa40fcc02b757a66e21e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: d9088d43cd4cff21574e1a9c48dd1d0fb15fe186
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: a480e7a181df10e84706b18cd636c4c6607c1134
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: ba4c0849e4201d353e8bd1de55915005b6329987
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: b6978b1ab474d99b7dc310d46e4e4b53f00d406c
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: 86aac144e7a7469d923dac3a7246f749f1f92ce9
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: 463c40b91748d66ebf465f2bd4303e198089f3ce
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: 22bf7c10fae81078f034bbd9ef0549b2e0b7de69
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: 0de032da00b7390c8218e18bd6f24ee67df193f0
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: 444ca6fa8b4f00241af9983a96be7e36dee2c039
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: fc95d54a3588efa5ffb60fc6c2d403899f91bcb1
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: 41e02d3d2fa19a5b67c429567925e788a024c3c9
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
