location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: develop
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: nodelet
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: 5068b6413372c309542a95ad522642d9406fa66f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: 1a08657785e4b9ea817a5528dee9ab25c01fe5cb
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: 5a70ed0791ddf92573853a629067d76d0242d9ed
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: c8d261948b89cd6bf3163d52fbf92461296b822f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: f0adf35e0415664ce33788a75007749583f678e8
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: b2bd175dde846a046c727785e25ff9833e679b09
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: 1da108271b2c20f3c16c9e6bc94cd9e807bbdc3c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: ba4c0849e4201d353e8bd1de55915005b6329987
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: d38bc39762a125310d0f39584598f4fd2292e986
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: af2c51f93e029b852637da6c0582beede87b12a5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: 8e234320d82f996eb3c1268cc5c232ae1eabdf75
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: 2e38e69c178f70f38cf8c8042cb95a7565f07344
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: e49c2d2b92b7b5d89e797ce420e1a36ad6616a03
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: 444ca6fa8b4f00241af9983a96be7e36dee2c039
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: 100473e9c1c6ed78fbf360af8eb7ab8f708d7883
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: c69ec6debffc69225e7a30b4dae3f90a02fd5bed
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
