location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: develop
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: nodelet
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: 5068b6413372c309542a95ad522642d9406fa66f
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: f02754b7b85401536d92ea3ec637eee01bce7bf4
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: 52f4d9e1b06d589aea68811d923867616d14e036
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: 1cf4d7e3b478d91a5d651496d0d52bbb15e78306
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: 6999cb668938ad063d9ceba33fa3d735cff3e48f
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: 09e7b78cf604ce274ca563a871a3cc178f61f514
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: 719b1600f56e2d2d8cf0290c5ec03a0f56d6bd7c
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: ba4c0849e4201d353e8bd1de55915005b6329987
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: cbbf6ab6d2633e618b9969576f759c6b826a4e37
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: 44006a9af2f7a484ed32c13d3247c06d8ffdf8ad
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: 6d52f166512211818bae76672688f2e7533a8a0e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: 22bf7c10fae81078f034bbd9ef0549b2e0b7de69
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: 7c47e7600b9cfc1ed942631ec5b2f82efd5fd2ce
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: 444ca6fa8b4f00241af9983a96be7e36dee2c039
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: 100473e9c1c6ed78fbf360af8eb7ab8f708d7883
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: 30152144b618624b02bd53b04e6fdf71908b9dff
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
