location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/nimbro_network.git
    name: nimbro_network
    rev: 4f8a7bbaf65e6bf2d927e04635be86397d28e295
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro_network
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/aloam.git
    name: aloam
    rev: 8d340be0cf20e7fd048e1fa3157132247bf56f99
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/aloam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/usb_cam.git
    name: usb_cam
    rev: ed55956bdd3d0ff0b0dfd0f854607f522acc4c26
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/usb_cam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools.git
    name: mrs_pcl_tools
    rev: 8b3344298c0b2719f494969852dabc2ff07bed79
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_optic_flow.git
    name: mrs_optic_flow
    rev: 14a95868367bb9300f4e3e2364d6756887d97b78
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_optic_flow
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/hector_slam.git
    name: hector_slam
    rev: bf0d1d4904d5145868a93a588f619ff5e8364fdc
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/hector_slam
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: c45c2d890dd4612a8c7602ab39db75835c9cf76a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader.git
    name: path_loader
    rev: 62af5de813dd0f76039b23e7edcf09ff3cb92d28
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/bluefox2.git
    name: bluefox2
    rev: ed4b2fa9ce92de5b0959a12b92b768308aa832b2
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/bluefox2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils.git
    name: mrs_utils
    rev: 0912914cc3b4c3c3a2c89fbb355673b8d61ed1cf
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: f4d7c9036e18b0e9b5637ab702d378050518b9b4
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_gazebo_extras_resources.git
    name: mrs_gazebo_extras_resources
    rev: e1b1da206f897ff2e36620ffa1d9e9608152cd1f
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_extras_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster.git
    name: ouster
    rev: d0432b77c8c74732983a77b853ac8ed01e7693d0
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/camera_base.git
    name: camera_base
    rev: 0721fe853451cdee47a63b59a328e216ae33c6c7
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/camera_base
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/rplidar_ros.git
    name: rplidar_ros
    rev: 628adaa6e6d62084bb4adc06ce62ceefbb9c5158
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/rplidar_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/realsense.git
    name: realsense
    rev: ff6cf6e3d3ad666b29ee20628c9f7cd417423411
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
